### PR TITLE
Rename game

### LINKED ISSUE #201: UI control for changing battle title
An often asked question is how to rename a battle. Should implement perhaps some edit button next to battle title that prompts the user to enter a new one.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #201

### CODE REVIEW

**Comment by 1-alex98** [comment]
Please rerun CI

**Comment by Jazcash** [comment]
Am I right in thinking that `$rename` only works for the lobby boss? Someone told me the other day (sorry if it was you) that it's possible to find out the lobby boss with `$rename`:

image

I think we should add `boss` as a property to `SpadsBattle` and then use that to only show this rename button if the current user is the boss. I guess this would mean BAR Lobby would have to send `$status` on joining and then parse the DM output, and then also keep track of the boss with a handler for the `* Boss mode enabled for Jazcash` message.

Let me know if you want to give that a shot, otherwise I'll have a go at it.

**Comment by 1-alex98** [comment]
I did not implement the parsing of $status because I assume that this be obsolete soon since the new protocol will offer new ways of doingt this

**Comment by 1-alex98** [comment]
@Jazcash should I implement the $status thing? If yes I can do so. But if there soon will be another way to do that I would rather wait and do it later

**Pull request merged**
